// OUT LED — product data (based on luzsollar.com/lj2 catalog, outlet versions)

window.OUTLED_PRODUCTS = [
  {
    id: "vent80",
    name: "Luminária LED + Ventilador de Teto 80W E27",
    cat: "ventiladores",
    catLabel: "Ventiladores",
    oldPrice: 62.40,
    price: 39.90,
    condition: "Pequeno arranhão na base. Funcionamento perfeito.",
    desc: "Luminária com ventilador integrado, controle remoto, 3 velocidades, soquete E27. Perfeita para sala e quarto.",
    icon: "fan",
  },
  {
    id: "proj1500",
    name: "Projetor LED Slim 1500W 6500K Bivolt IP65",
    cat: "projetores",
    catLabel: "Projetores",
    oldPrice: 390.62,
    price: 249.00,
    condition: "Sem caixa original. Produto novo, lacrado em saco plástico.",
    desc: "Alta potência, à prova d'água IP65, ideal para fachadas, quadras e áreas externas grandes.",
    icon: "projector",
  },
  {
    id: "proj1000",
    name: "Projetor LED Slim 1000W 6500K Bivolt IP65",
    cat: "projetores",
    catLabel: "Projetores",
    oldPrice: 185.94,
    price: 119.90,
    condition: "Riscos leves na carcaça traseira (não aparecem na instalação).",
    desc: "Iluminação industrial e externa, vida útil de 30.000h, branco frio 6500K.",
    icon: "projector",
  },
  {
    id: "proj600",
    name: "Projetor LED Slim 600W 6500K Bivolt IP65",
    cat: "projetores",
    catLabel: "Projetores",
    oldPrice: 77.97,
    price: 49.90,
    condition: "Sem caixa. Acompanha manual e parafusos.",
    desc: "Versátil para garagem, fachada, pátio. Alumínio fundido.",
    icon: "projector",
  },
  {
    id: "proj500",
    name: "Projetor LED Slim 500W 6500K Bivolt IP65",
    cat: "projetores",
    catLabel: "Projetores",
    oldPrice: 70.15,
    price: 44.90,
    condition: "Embalagem amassada — produto intacto.",
    desc: "Slim, leve, com vidro temperado e proteção total contra água.",
    icon: "projector",
  },
  {
    id: "proj400",
    name: "Projetor LED Slim 400W 6500K Bivolt IP65",
    cat: "projetores",
    catLabel: "Projetores",
    oldPrice: 54.54,
    price: 34.90,
    condition: "Pequena marca de adesivo na lateral.",
    desc: "Solução econômica e potente para áreas médias.",
    icon: "projector",
  },
  {
    id: "proj100red",
    name: "Projetor LED Slim 100W Vermelho Bivolt IP65",
    cat: "projetores",
    catLabel: "Projetores",
    oldPrice: 18.60,
    price: 11.90,
    condition: "Sem caixa.",
    desc: "Iluminação cênica vermelha. Perfeito para fachadas decorativas.",
    icon: "projector-color",
    color: "#ff5e3a",
  },
  {
    id: "proj100green",
    name: "Projetor LED Slim 100W Verde Bivolt IP65",
    cat: "projetores",
    catLabel: "Projetores",
    oldPrice: 18.60,
    price: 11.90,
    condition: "Sem caixa.",
    desc: "Luz verde para destaque de jardins e fachadas.",
    icon: "projector-color",
    color: "#2ade8b",
  },
  {
    id: "fitaled5m",
    name: "Fita LED 5m 12V 5050 Branco Frio",
    cat: "fitas",
    catLabel: "Fitas LED",
    oldPrice: 89.90,
    price: 54.90,
    condition: "Caixa danificada no transporte. Fita perfeita.",
    desc: "Fita LED autoadesiva 5m, alta luminosidade, com fonte e controlador inclusos.",
    icon: "strip",
  },
  {
    id: "fitaneon",
    name: "Fita Neon LED 5m Flexível RGB",
    cat: "fitas",
    catLabel: "Fitas LED",
    oldPrice: 149.90,
    price: 89.90,
    condition: "Pequeno corte na embalagem. Produto íntegro.",
    desc: "Aparência de neon real, flexível, controle por app. Externa IP67.",
    icon: "neon",
  },
  {
    id: "lamp9w",
    name: "Lâmpada LED Bulbo 9W E27 Bivolt",
    cat: "lampadas",
    catLabel: "Lâmpadas",
    oldPrice: 12.90,
    price: 6.90,
    condition: "Caixa amassada. Lâmpada nova.",
    desc: "Substitui 60W incandescente. Branco frio 6500K, 5 anos de garantia.",
    icon: "bulb",
  },
  {
    id: "lamp15w",
    name: "Lâmpada LED Bulbo 15W E27 Bivolt",
    cat: "lampadas",
    catLabel: "Lâmpadas",
    oldPrice: 19.90,
    price: 10.90,
    condition: "Sem caixa individual. Vendida em pacote de 4.",
    desc: "Alta luminosidade, ideal para sala e cozinha.",
    icon: "bulb",
  },
  {
    id: "spotlinear",
    name: "Spot Linear LED 30W 90cm Embutir",
    cat: "spots",
    catLabel: "Spots & Plafons",
    oldPrice: 220.00,
    price: 139.90,
    condition: "Risco visível em uma extremidade.",
    desc: "Iluminação técnica linear, perfil de alumínio, difusor leitoso.",
    icon: "linear",
  },
  {
    id: "plafon24",
    name: "Plafon LED Quadrado 24W Sobrepor",
    cat: "spots",
    catLabel: "Spots & Plafons",
    oldPrice: 89.00,
    price: 49.90,
    condition: "Marca de dedo no acrílico — limpa fácil.",
    desc: "Sobrepor 30x30cm, branco neutro 4000K, vida útil 25.000h.",
    icon: "plafon",
  },
  {
    id: "espeto20",
    name: "Espeto de Jardim LED 20W IP65",
    cat: "jardim",
    catLabel: "Jardim",
    oldPrice: 65.00,
    price: 34.90,
    condition: "Pintura preta com micro arranhões.",
    desc: "Direcionável, foco ajustável, à prova d'água. Para iluminação de plantas.",
    icon: "spike",
  },
  {
    id: "balizador",
    name: "Balizador LED 3W de Embutir Parede",
    cat: "jardim",
    catLabel: "Jardim",
    oldPrice: 45.00,
    price: 22.90,
    condition: "Sem caixa.",
    desc: "Para escadas, corredores e jardins. Acabamento fosco.",
    icon: "marker",
  },
];

window.OUTLED_CATEGORIES = [
  { id: "projetores", label: "Projetores", icon: "projector" },
  { id: "ventiladores", label: "Ventiladores", icon: "fan" },
  { id: "fitas", label: "Fitas LED", icon: "strip" },
  { id: "lampadas", label: "Lâmpadas", icon: "bulb" },
  { id: "spots", label: "Spots & Plafons", icon: "plafon" },
  { id: "jardim", label: "Jardim", icon: "spike" },
];
