// OUT LED — product data (based on luzsollar.com/lj2 catalog, outlet versions)

window.OUTLED_PRODUCTS = [
  {
    id: "vent80",
    name: "Luminária LED + Ventilador de Teto 80W E27",
    cat: "ventiladores",
    catLabel: "Ventiladores",
    oldPrice: 62.40,
    price: 39.90,
    condition: "Pequeno arranhão na base. Funcionamento perfeito.",
    desc: "Luminária com ventilador integrado, controle remoto, 3 velocidades, soquete E27. Perfeita para sala e quarto.",
    icon: "fan",
    img: "https://luzsollar.com/lj2/wp-content/uploads/2026/04/LUMINARIA_LED_E_VENTILADOR_80W_PRODUTO.png",
  },
  {
    id: "proj1500",
    name: "Projetor LED Slim 1500W 6500K Bivolt IP65",
    cat: "projetores",
    catLabel: "Projetores",
    oldPrice: 390.62,
    price: 249.00,
    condition: "Sem caixa original. Produto novo, lacrado em saco plástico.",
    desc: "Alta potência, à prova d'água IP65, ideal para fachadas, quadras e áreas externas grandes.",
    icon: "projector",
    img: "https://luzsollar.com/lj2/wp-content/uploads/2025/11/3396-5650-PROJETOR-LED-SLIM-1500W-6500K-BIVOLT-IP65.jpg",
  },
  {
    id: "proj1000",
    name: "Projetor LED Slim 1000W 6500K Bivolt IP65",
    cat: "projetores",
    catLabel: "Projetores",
    oldPrice: 185.94,
    price: 119.90,
    condition: "Riscos leves na carcaça traseira (não aparecem na instalação).",
    desc: "Iluminação industrial e externa, vida útil de 30.000h, branco frio 6500K.",
    icon: "projector",
    img: "https://luzsollar.com/lj2/wp-content/uploads/2025/11/3395-5649-PROJETOR-LED-SLIM-1000W-6500K-BIVOLT-IP65.jpg",
  },
  {
    id: "proj600",
    name: "Projetor LED Slim 600W 6500K Bivolt IP65",
    cat: "projetores",
    catLabel: "Projetores",
    oldPrice: 77.97,
    price: 49.90,
    condition: "Sem caixa. Acompanha manual e parafusos.",
    desc: "Versátil para garagem, fachada, pátio. Alumínio fundido.",
    icon: "projector",
    img: "https://luzsollar.com/lj2/wp-content/uploads/2025/11/3394-5648-PROJETOR-LED-SLIM-600W-6500K-BIVOLT-IP65.jpg",
  },
  {
    id: "proj500",
    name: "Projetor LED Slim 500W 6500K Bivolt IP65",
    cat: "projetores",
    catLabel: "Projetores",
    oldPrice: 70.15,
    price: 44.90,
    condition: "Embalagem amassada — produto intacto.",
    desc: "Slim, leve, com vidro temperado e proteção total contra água.",
    icon: "projector",
    img: "https://luzsollar.com/lj2/wp-content/uploads/2025/11/3393-5647-PROJETOR-LED-SLIM-500W-6500K-BIVOLT-IP65.jpg",
  },
  {
    id: "proj400",
    name: "Projetor LED Slim 400W 6500K Bivolt IP65",
    cat: "projetores",
    catLabel: "Projetores",
    oldPrice: 54.54,
    price: 34.90,
    condition: "Pequena marca de adesivo na lateral.",
    desc: "Solução econômica e potente para áreas médias.",
    icon: "projector",
    img: "https://luzsollar.com/lj2/wp-content/uploads/2025/11/3392-5646-PROJETOR-LED-SLIM-400W-6500K-BIVOLT-IP65.jpg",
  },
  {
    id: "proj100red",
    name: "Projetor LED Slim 100W Vermelho Bivolt IP65",
    cat: "projetores",
    catLabel: "Projetores",
    oldPrice: 18.60,
    price: 11.90,
    condition: "Sem caixa.",
    desc: "Iluminação cênica vermelha. Perfeito para fachadas decorativas.",
    icon: "projector-color",
    color: "#ff5e3a",
    img: "https://luzsollar.com/lj2/wp-content/uploads/2025/11/3389-5637-PROJETOR-LED-SLIM-100W-VERMELHO-BIVOLT-IP65.jpg",
  },
  {
    id: "proj100green",
    name: "Projetor LED Slim 100W Verde Bivolt IP65",
    cat: "projetores",
    catLabel: "Projetores",
    oldPrice: 18.60,
    price: 11.90,
    condition: "Sem caixa.",
    desc: "Luz verde para destaque de jardins e fachadas.",
    icon: "projector-color",
    color: "#2ade8b",
    img: "https://luzsollar.com/lj2/wp-content/uploads/2025/11/3387-5635-PROJETOR-LED-SLIM-100W-VERDE-BIVOLT-IP65.jpg",
  },
  {
    id: "fitaled5m",
    name: "Fita LED 2835 240 LEDs 20W 6500K",
    cat: "fitas",
    catLabel: "Fitas LED",
    oldPrice: 89.90,
    price: 54.90,
    condition: "Caixa danificada no transporte. Fita perfeita.",
    desc: "Fita LED autoadesiva alta densidade, branco frio, alta luminosidade.",
    icon: "strip",
    img: "https://luzsollar.com/lj2/wp-content/uploads/2025/10/fita-led-2835-240-leds.jpg",
  },
  {
    id: "fitaneon",
    name: "Fita LED 2835 120 LEDs 3000K",
    cat: "fitas",
    catLabel: "Fitas LED",
    oldPrice: 149.90,
    price: 89.90,
    condition: "Pequeno corte na embalagem. Produto íntegro.",
    desc: "Fita LED branco quente, perfeita para sancas e ambientes aconchegantes.",
    icon: "neon",
    img: "https://luzsollar.com/lj2/wp-content/uploads/2025/10/fita-led-2835-120-leds.jpg",
  },
  {
    id: "lamp9w",
    name: "Lâmpada LED Geladeira Leitosa 3W E14",
    cat: "lampadas",
    catLabel: "Lâmpadas",
    oldPrice: 12.90,
    price: 6.90,
    condition: "Caixa amassada. Lâmpada nova.",
    desc: "Compacta, ideal para geladeira e micro-ambientes. Soquete E14.",
    icon: "bulb",
    img: "https://luzsollar.com/lj2/wp-content/uploads/2026/04/7643-GELADEIRA-LEITOSA-3W-6500K-127-230v_LAMPADA.png",
  },
  {
    id: "lamp15w",
    name: "Lâmpada LED Geladeira Clara 7W E14",
    cat: "lampadas",
    catLabel: "Lâmpadas",
    oldPrice: 19.90,
    price: 10.90,
    condition: "Sem caixa individual.",
    desc: "Lâmpada clara de alta luminosidade, bivolt.",
    icon: "bulb",
    img: "https://luzsollar.com/lj2/wp-content/uploads/2026/04/7642-GELADEIRA-CLARA-7W-2400K-127-230v_PRODUTO.png",
  },
  {
    id: "spotlinear",
    name: "Pendente LED Wave 72W Dourado",
    cat: "spots",
    catLabel: "Spots & Plafons",
    oldPrice: 220.00,
    price: 139.90,
    condition: "Risco visível em uma extremidade.",
    desc: "Pendente moderno design wave, dourado, perfeito para sala de jantar e mesas.",
    icon: "linear",
    img: "https://luzsollar.com/lj2/wp-content/uploads/2026/03/7593.jpg",
  },
  {
    id: "plafon24",
    name: "Painel ABS Sobrepor QD 22x22 18W",
    cat: "spots",
    catLabel: "Spots & Plafons",
    oldPrice: 89.00,
    price: 49.90,
    condition: "Marca de dedo no acrílico — limpa fácil.",
    desc: "Plafon quadrado sobrepor, branco neutro 4000K, vida útil 25.000h.",
    icon: "plafon",
    img: "https://luzsollar.com/lj2/wp-content/uploads/2026/04/5476_PAINEL_SOBREPOR_QUADRADO.png",
  },
  {
    id: "espeto20",
    name: "Arandela LED Symphony 12W Dourado",
    cat: "jardim",
    catLabel: "Decoração",
    oldPrice: 65.00,
    price: 34.90,
    condition: "Pintura com micro arranhões.",
    desc: "Arandela decorativa moderna, luz quente, ideal para corredores e salas.",
    icon: "spike",
    img: "https://luzsollar.com/lj2/wp-content/uploads/2026/01/7565-arandela-symphony-12w.jpg",
  },
  {
    id: "balizador",
    name: "Arandela LED Twist 5W Dourado",
    cat: "jardim",
    catLabel: "Decoração",
    oldPrice: 45.00,
    price: 22.90,
    condition: "Sem caixa.",
    desc: "Design twist moderno, luz indireta, efeito de parede. Acabamento dourado premium.",
    icon: "marker",
    img: "https://luzsollar.com/lj2/wp-content/uploads/2026/01/7558-arandela-twist-dourado.jpg",
  },
];

window.OUTLED_CATEGORIES = [
  { id: "projetores", label: "Projetores", icon: "projector" },
  { id: "ventiladores", label: "Ventiladores", icon: "fan" },
  { id: "fitas", label: "Fitas LED", icon: "strip" },
  { id: "lampadas", label: "Lâmpadas", icon: "bulb" },
  { id: "spots", label: "Spots & Plafons", icon: "plafon" },
  { id: "jardim", label: "Decoração", icon: "spike" },
];
